[project]
name = "atosaac-virtual-partner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "atosaac", email = "165299099+atosaac@users.noreply.github.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
atosaac-virtual-partner = "atosaac_virtual_partner:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
